id: P000436
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:39:50.958080
source_metadata:
  id: bdr:W1KG24862
  title: དམངས་ཁྲོད་རྩོམ་རིག་རྣམ་བཤད།
  author: ''
  volumes:
    ae61eb003b204b1e954b7e283cb41f60:
      image_group_id: I1KG24864
      title: Volume 1 of dmangs khrod rtsom rig rnam bshad/
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
